[package]
name = "cli_space_factory_sim"
version = "0.1.0"
edition = "2024"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = "symbols"

[dependencies]
bincode = "2.0.1"
once_cell = "1.21.3"
phf = { version = "0.12.1", features = ["macros"] }

